name: ML CI Pipeline
description: Build, train, run API, smoke tests, push image
runs:
  using: "composite"
  steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      shell: bash
      run: docker build -t ml-backend-conda:latest ./backend

    - name: Train model
      shell: bash
      run: |
        mkdir -p backend/models
        docker run --rm -v "$PWD/backend/models:/app/models" \
          ml-backend-conda:latest \
          micromamba run -n ml-docker-api python -u train_model.py

    - name: Run API
      shell: bash
      run: |
        docker rm -f api 2>/dev/null || true
        docker run -d --name api -p 5000:5000 \
          -v "$PWD/backend/models:/app/models" \
          ml-backend-conda:latest \
          micromamba run -n ml-docker-api gunicorn -w 2 -b 0.0.0.0:5000 app:app
        sleep 10

    - name: Smoke tests
      shell: bash
      run: |
        curl -s http://localhost:5000/ | jq .
        curl -s -X POST http://localhost:5000/predict \
          -H "Content-Type: application/json" \
          -d '{"features":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}' | jq .

    - name: Push image
      shell: bash
      run: |
        docker tag ml-backend-conda:latest ghcr.io/${{ github.repository }}/ml-backend-conda:latest
        docker push ghcr.io/${{ github.repository }}/ml-backend-conda:latest
