name: especialidadmachinelearning
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - imbalanced-learn
  - pip
  - pip:
      - tensorflow[and-cuda]==2.15.*
      - shap
      - lime
      - nbformat
