name: especialidadmachinelearning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.5
  - numba=0.56.4
  - matplotlib
  - faker
  - pip
  - pip:
      - tqdm
      - scikit-learn
      - pandas
      - seaborn



