name: especialidadmachinelearning
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy

  # NLP básicos
  - regex
  - joblib

  - pip:
    - nltk
    - spacy
    - textblob
    - wordcloud
    - transformers
    - sentence-transformers
    - tokenizers




