version: "3.9"

services:
  trainer:
    image: ml-backend-conda:latest
    container_name: ml-trainer
    user: "${UID}:${GID}"                # ← corre como tu usuario del host
    environment:
      - MODEL_DIR=/app/models
      - DATASET=breast_cancer
      - RANDOM_STATE=42
    command: ["/opt/conda/envs/ml-docker-api/bin/python","-u","train_model.py"]
    volumes:
      - ./backend/models:/app/models:Z   # ← bind con etiqueta SELinux

  api:
    image: ml-backend-conda:latest
    container_name: ml-api
    user: "${UID}:${GID}"                # ← idem
    environment:
      - MODEL_DIR=/app/models
      - PORT=5000
    depends_on:
      - trainer
    ports:
      - "5000:5000"
    command: ["/opt/conda/envs/ml-docker-api/bin/gunicorn","-w","2","-b","0.0.0.0:5000","app:app"]
    volumes:
      - ./backend/models:/app/models:Z

