name: Multi-project CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        subdir: [ "Modulo10EvaModularMarcoParra" ]  # agrega más: "OtroProyecto", ...

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.subdir }}

    permissions:
      contents: read
      packages: write

    env:
      HOST_PORT: 8000
      CONTAINER_NAME: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq (for nicer JSON)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Show tree
        run: |
          echo "== Subproject: ${{ matrix.subdir }} =="
          ls -la
          echo "== backend =="
          ls -la backend

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags (lowercase repo & subdir)
        id: tags
        run: |
          IMAGE_BASE_LOWER=$(echo "ghcr.io/${{ github.repository }}/ml-backend-conda" | tr '[:upper:]' '[:lower:]')
          SAFE_TAG=$(echo '${{ matrix.subdir }}' | tr '[:upper:]/ ' '[:lower:]--')

          echo "image_base=$IMAGE_BASE_LOWER"         >> $GITHUB_OUTPUT
          echo "safe_tag=$SAFE_TAG"                   >> $GITHUB_OUTPUT
          echo "tag_sha=${IMAGE_BASE_LOWER}:${SAFE_TAG}-sha-${{ github.sha }}"   >> $GITHUB_OUTPUT
          echo "tag_latest=${IMAGE_BASE_LOWER}:${SAFE_TAG}-latest"               >> $GITHUB_OUTPUT

          echo "TAG_SHA=${IMAGE_BASE_LOWER}:${SAFE_TAG}-sha-${{ github.sha }}"
          echo "TAG_LATEST=${IMAGE_BASE_LOWER}:${SAFE_TAG}-latest"

      - name: Build Docker image
        run: |
          docker build -t "${{ steps.tags.outputs.tag_sha }}" -t "${{ steps.tags.outputs.tag_latest }}" ./backend

      - name: Train model (writes to backend/models)
        run: |
          mkdir -p backend/models
          docker run --rm \
            -v "$PWD/backend/models:/app/models" \
            "${{ steps.tags.outputs.tag_sha }}" \
            micromamba run -n ml-docker-api python -u train_model.py
          ls -lh backend/models

      - name: Run API container
        run: |
          docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true
          docker run -d --name "${CONTAINER_NAME}" \
            -p "${HOST_PORT}:5000" \
            -v "$PWD/backend/models:/app/models" \
            "${{ steps.tags.outputs.tag_sha }}" \
            micromamba run -n ml-docker-api gunicorn -w 2 -b 0.0.0.0:5000 app:app
          sleep 8
          docker logs --tail=100 "${CONTAINER_NAME}" || true

      - name: Smoke test - GET /
        run: |
          curl -fsS "http://localhost:${HOST_PORT}/" | jq .

      - name: Smoke test - POST /predict (zero vector)
        run: |
          curl -fsS -X POST "http://localhost:${HOST_PORT}/predict" \
            -H "Content-Type: application/json" \
            -d '{"features":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}' | jq .

      - name: Push image to GHCR
        run: |
          docker push "${{ steps.tags.outputs.tag_sha }}"
          docker push "${{ steps.tags.outputs.tag_latest }}"

      - name: Upload trained artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: models-${{ matrix.subdir }}
          path: |
            ${{ matrix.subdir }}/backend/models/model*.joblib
            ${{ matrix.subdir }}/backend/models/*.pkl
          if-no-files-found: ignore

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true
