name: Multi-project CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Agrega más subproyectos si los tienes
        subdir: [ "Modulo10EvaModularMarcoParra" ]

    # Todos los comandos se ejecutan dentro de la subcarpeta del subproyecto
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.subdir }}

    permissions:
      contents: read
      packages: write

    env:
      HOST_PORT: 8000           # Puerto del runner para mapear al 5000 del contenedor
      CONTAINER_NAME: api       # Nombre del contenedor de pruebas API

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq (pretty JSON)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Show tree
        run: |
          echo "== Subproject: ${{ matrix.subdir }} =="
          ls -la
          echo
          echo "== backend =="
          ls -la backend

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags (lowercase repo & subdir)
        id: tags
        run: |
          # Repositorio + nombre de imagen en minúsculas para GHCR
          IMAGE_BASE_LOWER=$(echo "ghcr.io/${{ github.repository }}/ml-backend-conda" | tr '[:upper:]' '[:lower:]')
          # Normaliza la subcarpeta a minúsculas y sin espacios/slashes
          SAFE_TAG=$(echo '${{ matrix.subdir }}' | tr '[:upper:]/ ' '[:lower:]--')

          echo "image_base=$IMAGE_BASE_LOWER" >> $GITHUB_OUTPUT
          echo "safe_tag=$SAFE_TAG"           >> $GITHUB_OUTPUT
          echo "tag_sha=${IMAGE_BASE_LOWER}:${SAFE_TAG}-sha-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "tag_latest=${IMAGE_BASE_LOWER}:${SAFE_TAG}-latest"             >> $GITHUB_OUTPUT

          echo "TAG_SHA=${IMAGE_BASE_LOWER}:${SAFE_TAG}-sha-${{ github.sha }}"
          echo "TAG_LATEST=${IMAGE_BASE_LOWER}:${SAFE_TAG}-latest"

      - name: Build Docker image
        run: |
          docker build -t "${{ steps.tags.outputs.tag_sha }}" -t "${{ steps.tags.outputs.tag_latest }}" ./backend

      # === FIX DE PERMISOS (host) + ENTRENAMIENTO COMO ROOT EN EL CONTENEDOR ===
      - name: Prepare writable model dir (fix perms on runner)
        run: |
          # Limpia/crea y da permisos amplios para que el contenedor pueda escribir
          rm -rf backend/models
          mkdir -p backend/models
          chmod -R 777 backend/models

      - name: Train model (writes to backend/models)
        run: |
          docker run --rm \
            -u 0:0 \
            -v "$PWD/backend/models:/app/models" \
            "${{ steps.tags.outputs.tag_sha }}" \
            micromamba run -n ml-docker-api python -u train_model.py

          # (opcional) Relaja permisos post-entrenamiento
          chmod -R a+rw backend/models

          echo "== Artifacts =="
          ls -l backend/models

      - name: Run API container
        run: |
          docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true
          docker run -d --name "${CONTAINER_NAME}" \
            -p "${HOST_PORT}:5000" \
            -v "$PWD/backend/models:/app/models" \
            "${{ steps.tags.outputs.tag_sha }}" \
            micromamba run -n ml-docker-api gunicorn -w 2 -b 0.0.0.0:5000 app:app

          # Espera breve y muestra logs para diagnóstico
          sleep 8
          docker logs --tail=100 "${CONTAINER_NAME}" || true

      - name: Smoke test - GET /
        run: |
          curl -fsS "http://localhost:${HOST_PORT}/" | jq .

      - name: Smoke test - POST /predict (zero vector)
        run: |
          curl -fsS -X POST "http://localhost:${HOST_PORT}/predict" \
            -H "Content-Type: application/json" \
            -d '{"features":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}' | jq .

      - name: Push image to GHCR
        run: |
          docker push "${{ steps.tags.outputs.tag_sha }}"
          docker push "${{ steps.tags.outputs.tag_latest }}"

      - name: Upload trained artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: models-${{ matrix.subdir }}
          path: |
            ${{ matrix.subdir }}/backend/models/model*.joblib
            ${{ matrix.subdir }}/backend/models/*.pkl
          if-no-files-found: ignore

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true
